console.log("\n\n")
console.log("     _             _   _                       ")
console.log('    | |           | | (_)                      ')
console.log(' ___| |_ __ _ _ __| |_ _ _ __   __ _           ')
console.log('/ __| __/ _` | "__| __| | "_ \ / _` |          ')
console.log('\\__ \ || (_| | |   | |_| | | | | (_| |_ _ _ _ _ ')
console.log('|___/\\__\\_,_|_|   \\__|_|_| |_| \\__, (_|_|_|_|_)')
console.log('                                __/ |          ')
console.log('                                |___/           ')
console.log("\n\n")